### PR TITLE
Update to scikit-build 0.5.0

### PR DESCRIPTION
**Pull request by jcfr**
**DO NOT MERGE**

The release if scikit-build hasn't been done yet ... the intent of this
PR is to test all the fixes and features.

### CODE REVIEW

**Comment by isuruf** [comment]
@jcfr, can you enable testing in CircleCI for your fork so that Linux tests are run?

**Comment by jcfr** [comment]
> can you enable testing in CircleCI for your fork so that Linux tests are run?

Thanks for the note, I missed that.

**Comment by isuruf** [comment]
It's because of a CircleCI issue, conda-forge/status#30

**Comment by jcfr** [comment]
Thanks for the pointer. We indeed had to deal with this for few projects. But since they are not associated with secret, enabling permissive build was okay.

Otherwise, here is the circleci: https://circleci.com/gh/jcfr/scikit-build-feedstock/1

Regarding AppVeyor, there is a long queue ... while there is [the rolling build feature](https://github.com/conda-forge/scikit-build-feedstock/blob/c1a0318fde0d9deffb9aed08f60a7b59e51c2b26/appveyor.yml#L48-L56), it is still too bad I can't cancel the obsolete builds ....

**Comment by isuruf** [comment]
You can cancel obsolete builds by logging into appveyor. You have to log in under `conda-forge`

**Comment by jcfr** [comment]
> You have to log under conda-forge

Great. Thanks.

I wasn't anticipating I was granted access. That is nice.
All set. Old build cancelled.

**Comment by isuruf** [comment]
@conda-forge/core can you delete the version d592c80 at https://anaconda.org/conda-forge/scikit-build/files? This was uploaded by mistake.

**Comment by jcfr** [comment]
> This was uploaded by mistake.

Indeed, earlier today I pushed a branch directly into to the repo instead of my fork.

I created an account (usernamed `jcfr`), how to get access so that I can delete the files ?


> Appveyor

It has been queuing for a full day ... I wonder if there is something wrong.

**Comment by jcfr** [comment]
Thanks for looking after the project while I am leaning the in and out of conda .. :smile:

**Comment by isuruf** [comment]
Only the core team has access to anaconda.org. Let's wait for them to fix it.
conda-forge has a big queue in appveyor today. You can check by going to page 29 of projects page of appveyor after logging in as `conda-forge`. This PR is at 18th in queue, so it will take some more time.

**Comment by jcfr** [comment]
> Only the core team has access to anaconda.org.

Makes sense.

>  page 29 of projects page of 

I see, thanks for the pointer

**Comment by jjhelmus** [comment]
@jcfr I changed the `d592c80` version packages from the `main` label to `broken`.  Users should not get these unless they explicitly include this label.  We prefer this to deleting packages in case a users happened to download the bad package and needs to recreate the issue.

**Comment by jcfr** [comment]
@jjhelmus Great. Thanks for your help with this.

Otherwise, next release is coming. If CI is green, I will merge this PR.

Cc: @isuruf

**Pull request merged**
