### PR TITLE
updated v0.9.0

### PR DESCRIPTION
**Pull request by jcfr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
Hmm basically everything is failing here

**Comment by henryiii** [comment]
Looks like it can't download `https://github.com/scikit-build/scikit-build/archive/0.9.0.tar.gz`, which is fine for me. Maybe a GitHub issue and should be rebuilt?

Edit: actually failing before that, in this line:

```
curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py
```

**Comment by henryiii** [comment]
Note: I assume this is on the old arch, no Python 3.7, etc. since no one ever fixed the new one? #20 that is.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by jcfr** [comment]
Closing. This was an attempt to "debug" failures associated with https://github.com/conda-forge/scikit-build-feedstock/pull/21 by incrementally bringing in changes.

**Pull request closed without merging**
