### PR TITLE
Update to 0.6.1

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender.

**Comment by xhochy** [comment]
The failing test is due to distutils being more verbose then expected. This is probably controlled by some setting in the build chain. I tend to disable this test in here instead of figuring out the root cause. @jcfr @jakirkham any opinion on that? (Running them locally inside a `conda build`, they pass).

**Comment by jcfr** [comment]
Thanks for the note. I will have a look later. 

Since the goal of scikit-build is to integrate setuptools and cmake, it is important to understand the root cause.

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/conda-forge/scikit-build-feedstock/pull/8

**Pull request closed without merging**
