### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.4

### PR DESCRIPTION
**Pull request by Luthaf**
I need this in https://github.com/conda-forge/chemfiles-python-feedstock/pull/6 to have a Python 3.6 version of scikit-build.

As updating scikit-build itself seems blocked on #4, I just rerendered the master branch, without changing the version number

### CODE REVIEW

**Comment by isuruf** [comment]
@Luthaf, can you cherry-pick https://github.com/conda-forge/scikit-build-feedstock/pull/3/commits/625db6918b2559c724cdeac64caf3ce083b551a3 ?

**Comment by Luthaf** [comment]
@isuruf done! I now have the same error locally as #4 with the `hide_listing` failure.

**Comment by jcfr** [comment]
FWWI, we are working on a new release including fixes (the hide-listing flag behavior should be fixed too)

**Comment by Luthaf** [comment]
@jcfr great! I was tracking the bug and pinned it to wheel using `distutils.log` and this log not being handled by scikit-build override. I hope this is the same bug that you fixed =)

**EDIT** nevermind, this is the one you fixed in https://github.com/scikit-build/scikit-build/commit/272f43a522fd550185dfa973b301ab3f500c56e8

Do you have any estimated release date ? No pressure, I can always release my code without support for Python 3.6, and add it back later.

**Pull request closed without merging**
