### PR TITLE
chore: add maintainers

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged) (not needed, no code changes)
*  Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding myself and @mayeut to the recipe, so we can help with #46.

### CODE REVIEW

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
@jcfr or... Actually, @thewtex, you aren't listed here, should I add you too?

**Comment by henryiii** [comment]
@jcfr, I didn't tag you correctly before, fixed now.

**Comment by henryiii** [comment]
@mayeut, can you verify you are okay to be added here?

**Comment by mayeut** [comment]
> can you verify you are okay to be added here?

I have no knowledge at all on conda-forge as of now. Although always eager to learn new things, I'm running out of time these days.

So I don't mind but I doubt I'll be of any help in the foreseeable future.

**Comment by jcfr** [comment]
Thanks @henryiii

**Pull request merged**
