### PR TITLE
Update to 0.7.1

### PR DESCRIPTION
**Pull request by Luthaf**
This replaces #4, #5, #6 and #7.

### CODE REVIEW

**Comment by Luthaf** [comment]
I manually disabled `test_setup_requires_keyword_include_cmake`: https://github.com/scikit-build/scikit-build/blob/0db863127cd0a6cadde0c1bffd9a40fdf304fe2d/tests/test_setup.py#L309-L337, as it tries to download cmake, which is not possible inside conda build/test environment.

**Comment by jcfr** [comment]
> as it tries to download cmake, which is not possible inside conda build/test environment.

Makes sense. I will look into having the test disabled if there is no network connection or if it is running in conda.

Do you know if conda set an environment variable that I could check ? 

> windows failure

I will have a look and also add testing with miniconda in the scikit-build proper.

**Comment by isuruf** [comment]
> Do you know if conda set an environment variable that I could check ?

`CONDA_BUILD`

**Comment by jcfr** [comment]
> as it tries to download cmake, which is not possible inside conda build/test environment.

Since I would like to mention it it in the `pytest.mark.skipif` reason, does some know where this is documented ? (faq entry or mailing list post ...)

I looked at https://conda-forge.org/docs/testing.html but didn't find it.

**Comment by jcfr** [comment]
xref https://github.com/scikit-build/scikit-build/pull/332

**Comment by isuruf** [comment]
https://github.com/conda/conda/issues/508

**Comment by moorepants** [comment]
What is the status on this PR? I see the windows build is failing but am not familiar enough to know what exactly is going on.

**Comment by jcfr** [comment]
The issue was fixed [in master](https://scikit-build.readthedocs.io/en/latest/changes.html#tests), after cutting release `0.8.0`, this will be addressed.

**Comment by moorepants** [comment]
Great thanks. We'd love to have this for our slycot builds.

**Comment by jcfr** [comment]
New release of scikit-build has been pushed to pypi.

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/conda-forge/scikit-build-feedstock/pull/14

**Pull request closed without merging**
